### ISSUE TITLE
Return type of public static method from exported class has or is using private name 'BaseWithPlugins'

### ISSUE THREAD

**Issue by gr2m** [gr2m/javascript-plugin-architecture-with-typescript-definitions#1]
running `tsc index.ts --declaration` currently throws an error

```
> tsc index.ts --declaration

index.ts:25:10 - error TS4052: Return type of public static method from exported class has or is using private name 'BaseWithPlugins'.

25   static plugin<T extends TestPlugin | TestPlugin[]>(plugin: T) {
            ~~~~~~
```

I'm not sure how to fix that problem yet, help much appreciated!

**Comment by karol-majewski** [comment]
Do this:

```diff
- class BaseWithPlugins extends this {
+ const BaseWithPlugins = class extends this {
```

but don't ask me why this works because I have no idea. 🙏

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
