### ISSUE TITLE
Unknown keys on instance should not be typed as `any` when instantiating from `Base.defaults()` or `Base.plugin()`

### ISSUE THREAD

**Issue by gr2m** [gr2m/javascript-plugin-architecture-with-typescript-definitions#31]
Example

```ts
const base = new Base()

// TS complains as expected
base.unknown

const BaseWithDefaults = Base.defaults({})
const baseWithDefaults = new BaseWithDefaults

// TS does _not_ complain, `.unknown` is typed as `any`, and it shouldn't
baseWithDefaults.unknown
```

The problems are these two lines from the resulting `.d.ts` file

https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/blob/3e0da094049c84a849159dab9455a926aa4ea6b3/index.d.ts#L22

https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/blob/3e0da094049c84a849159dab9455a926aa4ea6b3/index.d.ts#L28

I don't quite understand whey they are coming from, and how I can change them to at least `[x: string]: unknown`.

Any idea?

Here is a [playground](https://www.typescriptlang.org/play?#code/PTAECgVBlB5BVASgYQKKmbAIu2AxSMACwBcSAHAZwC4QBzASxKIFcAjAOgGMB7AW2B0ATgCYBAKwCGAN0mUuQhuRIBacgBsWjAHYrJQrkSYBTLiRZDjKgO5MiKkgE9yx+YuUqAJsYBmDbUwMPNqUwGzqPGzAfHIkxkLAlAbA-t4AHhwklITg4E4uoLDKQSGgALygAN7goKAA2gDWxo7UoJQkitp0ALqtLNoN2jzW2gDc4AC+43nOxqAAguQMqGlxISXlVfVNLW0d-j19A0MjoFMzBQAqriQACpo6mwAUNaD+7ZLaXMatAEJyxgANK8eMVgjRCmCQuAAJTlAB8CyWKzWlA2AB9QP1vH5tMZPON8nNkOCOiwzDwhAAeS6Iip46ygJ4cFn6OgQz6OOrdOFlRGXabAABUQpqQtAAAFJCxmJTQKQKDQQB8uA0eNJ4j4ItZuPxgCxKPFQiIABwmgDsIgAjCbgOIuJJ1AAvMWSw1zBVUWiJEiSVXqzXa3UCSTAACsAAYAMzmsOmgBswCt0ZEkajIjFwAuc3gAWClx4AEltHEhIazCUqbmSnSma9q8FQMZVsZtJ5KKBOaAAPxMtksPitkitBvaXmI6Q8BieUCtPEaoSwpsttsdp79wcl1r+HzxUDF0vlkglcegSfT0BQLLqfzDzwMSiScJWG94uc8FT9A34169g9G0xj2CV452MBdpiJBZtEcPB+grRsKmZVkhHZVpOVPTkINmUBEGMcwhG0S5ZlgHwaWXNZ2ygmC4KA7RQExeZoNgr5aO5WtLnI1tKMY6iWJKX8cLwixCNmGl4RA0AOObCiOx45j4O0bkBNHAt-zLQDK1w-CRJcGk6m0Ac2Hibp4XE2pQPA3Jm3ISkSFALh1DkDt-kNKpXg+Y8uFADQtHeVprnae5fMU7pNm5cZag8hgvJ8nQqVeWpoE41cMFJIRyRISkqU5READItlivzO2g7kzmBWpakuK1ksogK7gefxyoqy4RBqjs6qCnQlNqeEnmYB9WmgQFvIa7QrX8q1hpZDhJE8e9aMdTqipauFqgq+zSXsixLBLJbSgqfrKA4QqQgiir1Dw0AGT2iEng60b6KxNtfH8fEYVKio6gSiqTsm77amm2b5pKRbRsoJram6aZ1t4EI7Jc4wAHU7BuzYHKctrQEOtz1si31PJG4KOwqLhtqHG7dS+SQSBeXGKuusGOD8dRSyeJ4TtPABCUmhB2+qiY4fwHJYbxKHZ0aYRhf7QBhM7anOb7LG00AEeR5hUbkLHZh4HwVYBNWiFR3LpZJOH0opakVKLEsAIUqktOEoiXBImkrTywTtKd4wXZa0z4TOiZcjx6notAHFpRZygqSS6SuI7U32nNzLqRy3rDsG4bw5YSPWiKWjKFW77YfaPXDTVrBfAjrI0ccygO1jlLsbW3Hi7JC2kJmlCORKnkcbptoWBcIQnlgNhxEAma64YOhtCeSoJkzyvs6yYa2UoOoI1C9FMXnyW5YqwP1oV9aleE0ukaYCufCrygA6DjazYyyknlBfPc6hYmqgmQv1sOjhX5KJ-AB4JoYVSgJIcgGhHCEx0NkdaUBPRKh9H6NUC4tTDGDMAUMVp4xRgACxhitJaIum10Z1wTm3ZOmw-6tyTnKTWRIdbn33mQygFC6FCGOozHwlJUB+iIGzDmCI+7rVHuPMwk80Qzz6kYcGMD-AyIfMNYBIQ97fW-nfEEH93753GIHQgEAoDADgEgNAGBsCoByAYgABmwAE1i3hw0+N8MOPBXBXR4HZIefAmBPUGMMOiOxsit1AHY1y9JjCMgRk8KWBiJRZBUNZQCiTeZyluEIUE8QnCgAAOT9H8SMHJrj3FDDss2B8dlGyQRyQjHJHAngiCjFGAAnFLMJxgOD5JONoXIITVZ2CvjfTYCMOBZ0jnPb+4AQntINoM5en8GTn1mUvSOuQoCoFSUIVotj9YDJWVkBxng3Edm8b4rpATQBBLiQkpJZgUkZKEKAaxnTjgBIcZQIgPBs4zlKaEuYRIZya2sZyax4AZl7OvvMl5BSelTM2v09WD0KgjJOmzU8EzJZwrhqE3ZiLgqbEWQiw2o01lgA2Q87Z4K8U6EOcc7y8QfF2XOacK5UB4mUESWkFwdz4gPKedC7p7zPnfI8XZIyWsXCAo7MC6CoKqXEuCgKgJQA) with the full source code

**Comment by Andarist** [comment]
Can you drop the generic contraint `S extends Constructor<any>`? I don't quite see why you need it there - you shouldn't be able to parameterize it but rather the base class should flows/compose through layers of `.defaults()` calls etc. Or am I missing something?

Without it works:
[TS playground](https://www.typescriptlang.org/play?#code/PTAECgVBlB5BVASgYQKKmbAIu2AxSMACwBcSAHAZwC4QBzASxKIFcAjAOgGMB7AW2B0ATgCYBAKwCGAN0mUuQhuRIBacgBsWjAHYrJQrkSYBTLiRZDjKgO5MiKkgE9yx+YuUqAJsYBmDbUwMPNqUwGzqPGzAfHIkxkLAlAbA-t4AHhwklITg4E4uoLDKQSGgALygAN7goKAA2gDWxo7UoJQkitp0ALqtLNoN2jzW2gDc4AC+43nOxqAAguQMqGlxISXlVfVNLW0d-j19A0MjoFMzBQAqriQACpo6mwAUNaD+7ZLaXMatAEJyxgANK8eMVgjRCmCQuAAJTlAB8CyWKzWlA2AB9QP1vH5tMZPON8nNkOCOiwzDwhAAeS6Iip46ygJ4cFn6OgQz6OOrdOFlRGXabAABUQpqQtAAAFJCxmJTQKQKDQQB8uA0eNJ4j4ItZuPxgCxKPFQiIABwmgDsIgAjCbgOIuJJ1AAvMWSw1zBVUWiJEiSVXqzXa3UCSTAACsAAYAMzmsOmgBswCt0ZEkajIjFwAuc3gAWClx4AEltHEhIazCUqbmSnSma9q8FQMZVsZtJ5KKBOaAAPxMtksPitkitBvaXmI6Q8BieUCtPEaoSwpsttsdp79wcl1r+HzxUDF0vlkglcegSfT0BQLLqfzDzwMSiScJWG94uc8FT9A34169g9G0xj2CV452MBdpiJBZtEcPB+grRsKmZVkhHZVpOVPTkINmUBEGMcwhG0S5ZlgHwaWXNZ2ygmC4KA7RQExeZoNgr5aO5WtLnI1tKMY6iWJKX8cLwixCNmGl4RA0AOObCiOx45j4O0bkBNHAt-zLQDK1w-CRJcGk6m0Ac2Hibp4XE2pQPA3Jm3ISkSFALh1DkDt-kNKpXg+Y8uFADQtHeVprnae5fMU7pNm5cZag8hgvJ8nQqVeWpLitTjV0km4gp0YFakSkQUsogK7gefwlNqeEnli-wrX8q1AVAFkOEkTx71ox0Mr8ySRDhapsvs0l7IsSwSza0oKmYB8OAqkIIuy9Q8NABlhohJ4CuG+isTbXx-HxGFuTChLssmmr9tqerGuakpWqKkIsuy7pph63gQjslzjAAdTsRbNgcpy8o7MaO26nq9kkTzvKujsKi4Aah0W3UvhBl4geyhbwY4Px1FLJ5yqu08AEIoaEQbCuCygOH8ByWG8ShseC3GYThORO2gkqgZhabanOfbLG00AXve5hPsZokeB8XmAX5ohPoAMmOjBSSEckSEpKs80IosSwAhSqS04SiJcEiaStREpcE7S9eMA3LhEUz4WmiZcki31QZxaUMepl2WDd1oiloyguv2x72jFw1+awXxXayL7HMoDtpK4v6jAB2XA7JCkhCQhqUI5ZmeTcpHIpYFx09gNhxEAhqY4YOhtCeSoJlqj23dqtlKDqCNQvRTE6-p9nsvtnrOZ67nhODt6mDDnwI8oO2Hd6p6FbTp5QV972oQhqoJn9nr-o4ZeSnXvfwXu7KoEkcgNEcMGSf2qBPSVH0-TVBctWGYNgFDK14yjAAWMMrUtAOfVvoxxJPPRWcpRqJzhu0BeSshCdj+rMEWo9e7AMoKAmB4ChATVRj4SkqA-RECxpNU8gMeolzLmYCuaJq5PH+rVSadDE61UPiEHu+1N4zxBGvVevtxj20IBAKAwA4BIDQBgbAqAciCIAAZsABDIt4T1PjfFAJ4Hgrh5o8DskXPgTB1qDGGHRHY2QU6gHka5ekxhGQvSeDCXIFjjC7zXrkKAEosgqGsoBTxhM5S3CEKCeIThQAAHJ+iGJGCEtRGiOxDDss2B8dlGyQRCS9EJHAngiCjFGAAnPYxxHBwknG0LkMxfM7ATynpsF6HBG5ZFrpvcAZjHES0qZ7SOVibHiwqeHdp2RwAtJ6ZPPpzjfauLAKgXxQhWhyO6cwNpbtFHqM0bo-RRSjGgBMYI9xlBPFpBcGYHxAT4EyMKccIxijKBEB4J7GccTzFzCJDORmMjOQyIGXMogCyshnIiSUppfVykCyutUgEODgpY1PA0+mAKnrmM+atTpo8JbDXGaASZxyZmDOBcFJZMTvLxD0XZdZpwtluI8V4w58RjmgFOSS7Qlzrm3K0XZIyoAnkINpW8j5IcPpXV+cUoAA) (with some extra casting in the static `plugin` method)

**Comment by gr2m** [comment]
Thanks a lot for looking into it!

> Can you drop the generic contraint `S extends Constructor<any>`?

It came from here:
https://stackoverflow.com/questions/58636914/chaining-static-plugin-class-method-to-extend-instance-apis-multiple-times/58706699#58706699

With your changes, `Base.plugin(myPlugin).defaults(options)` no longer works. This test is now failing

https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/blob/3e0da094049c84a849159dab9455a926aa4ea6b3/test.ts#L53-L68

There is the [TS Playground](https://www.typescriptlang.org/play?#code/PTAECgVBlB5BVASgYQKKmbAIu2AxSMACwBcSAHAZwC4QBzASxKIFcAjAOgGMB7AW2B0ATgCYBAKwCGAN0mUuQhuRIBacgBsWjAHYrJQrkSYBTLiRZDjKgO5MiKkgE9yx+YuUqAJsYBmDbUwMPNqUwGzqPGzAfHIkxkLAlAbA-t4AHhwklITg4E4uoLDKQSGgALygAN7goKAA2gDWxo7UoJQkitp0ALqtLNoN2jzW2gDc4AC+43nOxqAAguQMqGlxISXlVfVNLW0d-j19A0MjoFMzBQAqriQACpo6mwAUNaD+7ZLaXMatAEJyxgANK8eMVgjRCmCQuAAJTlAB8CyWKzWlA2AB9QP1vH5tMZPON8nNkOCOiwzDwhAAeS6Iip46ygJ4cFn6OgQz6OOrdOFlRGXabAABUQpqQtAAAFJCxmJTQKQKDQQB8uA0eNJ4j4ItZuPxgCxKPFQiIABwmgDsIgAjCbgOIuJJ1AAvMWSw1zBVUWiJEiSVXqzXa3UCSTAACsAAYAMzmsOmgBswCt0ZEkajIjFwAuc3gAWClx4AEltHEhIazCUqbmSnSma9q8FQMZVsZtJ5KKBOaAAPxMtksPitkitBvaXmI6Q8BieUCtPEaoSwpsttsdp79wcl1r+HzxUDF0vlkglcegSfT0BQLLqfzDzwMSiScJWG94uc8FT9A34169g9G0xj2CV452MBdpiJBZtEcPB+grRsKmZVkhHZVpOVPTkINmUBEGMcwhG0S5ZlgHwaWXNZ2ygmC4KA7RQExeZoNgr5aO5WtLnI1tKMY6iWJKX8cLwixCNmGl4RA0AOObCiOx45j4O0bkBNHAt-zLQDK1w-CRJcGk6m0Ac2Hibp4XE2pQPA3Jm3ISkSFALh1DkDt-kNKpXg+Y8uFADQtHeVprnae5fMU7pNm5cZag8hgvJ8nQqVeWpLitTjV0km4gp0YFakSkQUsogK7gefwlNqeEnli-wrX8q1AVAFkOEkTx71ox0Mr8ySRDhapsvs0l7IsSwSza0oKmYB8OAqkIIuy9Q8NABlhohJ4CuG+isTbXx-HxGFuTChLssmmr9tqerGuakpWqKkIsuy7pph63gQjslzjAAdTsRbNgcpy8o7MaO26nq9kkTzvKujsKi4Aah0W3UvhBl4geyhbwY4Px1FLJ5yqu08AEIoaEQbCuCygOH8ByWG8ShseC3GYThORO2gkqgZhabanOfbLG00AXve5hPsZokeB8XmAX5ohPoAMmOjBSSEckSEpKs80IosSwAhSqS04SiJcEiaStREpcE7S9eMA3LhEUz4WmiZcki31QZxaUMepl2WDd1oiloyguv2x72jFw1+awXxXayL7HMoDtpK4v6jAB2XA7JCkhCQhqUI5ZmeTcpHIpYFx09gNhxEAhqY4YOhtCeSoJlqj23dqtlKDqCNQvRTE6-p9nsvtnrOZ67nhODt6mDDnwI8oO2Hd6p6FbTp5QV972oQhqoJn9nr-o4ZeSnXvfwXu7KoEkcgNEcMGSf2qBPSVH0-TVBctWGYNgFDK14yjAAWMMrUtAOfVvoxxJPPRWcpRqJzhu0BeSshCdj+rMEWo9e7AMoKAmB4ChATVRj4SkqA-RECxpNU8gMeolzLmYCuaJq5PH+rVSadDE61UPiEHu+1N4zxBGvVevtxj20IBAKAwA4BIDQBgbAqAciCIAAZsABDIt4T1PjfFAJ4Hgrh5o8DskXPgTB1qDGGHRHY2QU6gHka5ekxhGQvSeDCXIFjjC7zXrkKAEosgqGsoBTxhM5S3CEKCeIThQAAHJ+iGJGCEtRGiOxDDss2B8dlGyQRCS9EJHAngiCjFGAAnPYxxHBwknG0LkMxfM7ATynpsF6HBG5ZFrpvcAZjHES0qZ7SOVibHiwqeHdp2RwAtJ6ZPPpzjfauLAKgXxQhWhyO6cwNpbtFHqM0bo-RRSjGgBMYI9xlBPFpBcGYHxAT4EyMKccIxijKBEB4J7GccTzFzCJDORmMjOQyIGXMogCyshnIiSUppfVykCyutUgEODgpY1PA0+mAKnrmM+atTpo8JbDXGaASZxyZmDOBcFJZMTvLxD0XZdZpwtluI8V4w58RjmgFOSS7Qlzrm3K0XZIyoAnkINpW8j5IcPpXV+cU0pfU8E8ERUyOI7Q-gAlIa8YeBE87ZRFa0OxCJQAACIRVqpuucTmZSEVXUYp4b568amMJVXyJklRQBKvVZqs49Nam9LdrXV48inStDVZ4SQTotWTDZkKuF7xfRfGMMlJFQLJYGrbMaux0wg0qNDWjHgPAgA) to showcase the problem

**Comment by Andarist** [comment]
Oh, I thought that TS would be smart enough to understand that `this` type should infer from creates subclasses 😬 

Casting return values with `typeof this` somewhat works but I guess this might also be incorrect for some other reason:
[TS playground](https://www.typescriptlang.org/play?#code/PTAECgVBlB5BVASgYQKKmbAIu2AxSMACwBcSAHAZwC4QBzASxKIFcAjAOgGMB7AW2B0ATgCYBAKwCGAN0mUuQhuRIBacgBsWjAHYrJQrkSYBTLiRZDjKgO5MiKkgE9yx+YuUqAJsYBmDbUwMPNqUwGzqPGzAfHIkxkLAlAbA-t4AHhwklITg4E4uoLDKQSGgALygAN7goKAA2gDWxo7UoJQkitp0ALqtLNoN2jzW2gDc4AC+43nOxqAAguQMqGlxISXlVfVNLW0d-j19A0MjoFMzBQAqriQACpo6mwAUNaD+7ZLaXMatAEJyxgANK8eMVgjRCmCQuAAJTlAB8CyWKzWlA2AB9QP1vH5tMZPON8nNkOCOiwzDwhAAeS6Iip46ygJ4cFn6OgQz6OOrdOFlRGXabAABUQpqQtAAAFJCxmJTQKQKDQQB8uA0eNJ4j4ItZuPxgCxKPFQiIABwmgDsIgAjCbgOIuJJ1AAvMWSw1zBVUWiJEiSVXqzXa3UCSTAACsAAYAMzmsOmgBswCt0ZEkajIjFwAuc3gAWClx4AEltHEhIazCUqbmSnSma9q8FQMZVsZtJ5KKBOaAAPxMtksPitkitBvaXmI6Q8BieUCtPEaoSwpsttsdp79wcl1r+HzxUDF0vlkglcegSfT0BQLLqfzDzwMSiScJWG94uc8FT9A34169g9G0xj2CV452MBdpiJBZtEcPB+grRsKmZVkhHZVpOVPTkINmUBEGMcwhG0S5ZlgHwaWXNZ2ygmC4KA7RQExeZoNgr5aO5WtLnI1tKMY6iWJKX8cLwixCNmGl4RA0AOObCiOx45j4O0bkBNHAt-zLQDK1w-CRJcGk6m0Ac2Hibp4XE2pQPA3Jm3ISkSFALh1DkDt-kNKpXg+Y8uFADQtHeVprnae5fMU7pNm5cZag8hgvJ8nQqVeWpoE41cMFJIRyRISkqU5READItlivzO2g7kzmBWpakuK1ksogK7gefxyoqy4RBqjs6qCnQlNqeEnmYB9WmgQFvIa7QrX8q1hpZDhJE8e9aMdTqipauFqgq+zSXsixLBLJbSgqfrKA4QqQgiir1Dw0AGT2iEng60b6KxNtfH8fEYVKio6gSiqTsm77amm2b5pKRbRsoJram6aZ1t4EI7Jc4wAHU7BuzYHKctrQEOtz1si31PJG4KOwqLhtqHG7dS+SQSBeXGKuusGOD8dRSyeJ4TtPABCUmhB2+qiY4fwHJYbxKHZ0aYRhf7QBhM7anOb7LG00AEeR5hUbkLHZh4HwsaMDt8sqQmdA5ErQomUBculkk4fSilqRUosSwAhSqS04SiJcEiaStPLBO0z3jG9lrTPhM6JlyPHqei0AcWlFnKCpJLpK4jsbfaO3MupHLesOwbhrjlgE9aIpaMoVbvth9oVYBNWsF8eOsjRxzKA7FOUuxtbcarsl7aQmaUNNrkeRxum2hYFwhCeWA2HEQCZtbhg6G0J5KgmAuG6LrJhrZSg6gjUL0UxNfJbliqI-WhX1qV4Sa8NOvN4TzsOyJHW9YfcPI4222MspJ5QTLiXKExMqgTArutQ6HAAElBAdA8E0MKpQEkOQDQjhjbvG+lAT0SofR+jVAuLUwxgzAFDFaeMUYAAsYYrSWkrptdGrd069yzpsSBPdM5yk1q-XWCMz4MMoEwjhQhjqMx8JSVAfoiBsw5giUe60Z5zzMAvNEy8+r62GidNRD5hpwJCKfb6YDP4gmAUAsu4wI6EAgFAYAcAkBoAwNgVAORLEAAM2AAhcW8OGnxvixx4K4K6PA7KTz4EwJ6gxhh0R2NkHuoB3GuXpMYRkCMnhS0sRKLIKhrKASybzOUtwhCgniE4UAAByfoESRilL8QEoYdlmwPjso2SCpSEalI4E8EQUYowAE4pbxOMBwCpJxtC5FiarOw9cfCNxAQjDghcE6rzAeAWJAy1ZECmTMzYDI75I0mY-LIuQoCoDyUIVobja77OmVvSgnjPD+I7CEsJwzImgGiekzJ2SzC5MKUIUALihnHEiZ4ygRAeBFxnHUuJcwiQzk1i4zkLjwBrKuTMwFlTRkrM2hM9WD0KhzM0ak2RSzJZYrhnEy5uLgrbKSbs9Ze0jlgBOb885KKqU6DuQ87y8RQl2Reacd5UAMmUCyWkFw3z4i-P+eikZIKwUQsCXZIyWsXBwo7Ai6CSK2VED2jKyJuQyXVxxTq0ajFPCbJuZsAlo02anlXqAMRPBWgUNamAqW8yDliy7u4p0rQABEnhJBOj9cCQxYzNrvF9F8Yw1VEnJMpSa4KZqLWLNlrkSNPiY1Mx4DwIAA)

**Comment by gr2m** [comment]
Thanks, that works with my tests so far. I'll ship it in @octokit, we'll see how it goes!

**Comment by Andarist** [comment]
Ping me if you encounter any problems - quite frankly this API was somewhat hard to grok at first for me and I was unsure what are exact constraints that you want to achieve so it's hard for me to assess if this will truly "just work" for everything you want to achieve.

I'm not entirely sure why this was the problem but I think this was because you were using mixin types/feature (I was not aware that TS supported this~ up to this point) and that using those triggered some different code path in TS that resulted in this. My "fix" just works around this by not using those mixin semantics and just implementing "mixin" by hand at the type-level.

**Comment by Odin61** [comment]
- [ ] npm shrinkwrap
