### ISSUE TITLE
Replace TypeScript source code + build step with ESM JavaScript and hand-written `index.d.ts` and make Constructor options extendable by plugins

### ISSUE THREAD

**Issue by gr2m** [gr2m/javascript-plugin-architecture-with-typescript-definitions#45]
optimize the code of `index.js` and `index.d.ts` instead.

I think it would also be cool if plugins could extend the constructor options, so something like this would be possible

```js
import { Base } from "javascript-plugin-architecture-with-typescript-definitions";
import { myPlugin } from "my-plugin"

const MyThing = Base.plugin(myPlugin)

const thing = new MyThing({
  myPlugin: {
    some: "option"
  }
})
```

By importing from "my-plugin", the constructor options for `Base` would be expanded with something a type for the `myPlugin` key

I'm not sure how to do this, but I think it's possible by [merging interfaces](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces)?

**Comment by orta** [comment]
I think I can do this (I documented it for Jest) - should be this: https://jestjs.io/docs/expect#expectextendmatchers

**Comment by gr2m** [comment]
I'll check it out!

Would you be available to pair on this next week Thursday (June 17th)? I usually do a show at 1pm pacific, but happy to do it earlier, whatever works for you

**Comment by orta** [comment]
I can do it, I'll be a little off my game because I'm also a guest on a podcast earlier that same day I think

**Comment by gr2m** [comment]
#51 was just the part of rewriting the source to a native ES Module and remove replace the TypeScript source with JS + `index.d.ts`

**Comment by gr2m** [comment]
That's done enough :)
